### PR TITLE
Port to Python3

### PR DESCRIPTION
**Pull request by anmol27katyani**
- Minor changes only
- authored <anmolmishra.jiit@gmail.com>

### CODE REVIEW

**Comment by quozl** [comment]
Thanks for the patch.  I've looked at the [changes](https://github.com/sugarlabs/help-activity/pull/4/files).  I'm having difficulty understanding these changes;

* [x] your adding of several `.DS_Store` files,
* [x] your `sugar-activit3y` change,
* [ ] your changes to the translatable strings template file `Help.pot`,
* [ ] your changes to two translated strings files `Help.po`.

Could you check again that the changes you intended were added to the commit, and no others?

**Comment by rhl-bthr** [comment]
Thanks, 
I tried running this patch by calling `sugar-activity3` from the terminal. Here are the logs:

```shell
Traceback (most recent call last):
  File "/usr/bin/sugar-activity3", line 5, in <module>
    activityinstance.main()
  File "/usr/lib/python3/dist-packages/sugar3/activity/activityinstance.py", line 160, in main
    splitted_module = activity_class.rsplit('.', 1)
AttributeError: 'NoneType' object has no attribute 'rsplit'
```

**Comment by quozl** [comment]
@Pro-Panda, that's probably because the `startswith` does not evaluate to `True`; https://github.com/Pro-Panda/sugar-toolkit-gtk3/blob/python3-port/src/sugar3/activity/activityinstance.py#L127

```python
    if not activity_class:
        if bundle.get_command().startswith('sugar-activity'):
            activity_class = bundle.get_command().split(" ")[1]
```

If you think the toolkit should do a better job at explaining that, feel free to propose a change.

**Comment by rhl-bthr** [comment]
@quozl sure, thanks.

**Comment by anmol27katyani** [comment]
@quozl , When I cloned this repository, there are few Changes not staged for commit. ".DS_Store", "Help.pot" and "Help.po" are the changes included in that. Please check them and "sugar-activity3y" was my typo blunder. I'll try not to carry it on further.

**Comment by quozl** [comment]
@octamois, please test before commit; 17c3a7e does not fix the typo, and could not have worked.

I don't understand what you mean by changes not staged for commit; I didn't change the files on your system, only you could have done that.  Somehow you added them to your commit, against your own wishes.  I don't know how you did that, but perhaps you used `git add -a` in the hope that the only things you changed were what you intended to change.  You'll need to remove those unintended changes before we can merge.

**Comment by quozl** [comment]
You need to remove those unintended changes; not remove the files altogether.  Your [aggregate change](https://github.com/sugarlabs/help-activity/pull/4/files) shows you are removing `po/Help.pot` and `translated_po/es/Help.po`, and still have changes you've made to `translated_po/ht/Help.po`.  Please read the aggregate change carefully.  I've no idea why you are changing those files; they _do_ look more recent, did you get them from somewhere interesting?  Perhaps they could be the subject of another pull request.

**Comment by tony37** [comment]
This activity displays static web sites. I would seem better to port 
this as a sugar web activity than to Python3.

Tony

**Comment by quozl** [comment]
We have no Sugar Web developers willing to work on the Sugar environment, so porting to Python 3 is simplest alternative.  Also, there's common functionality between the Help Activity and the <kbd>ctrl-shift-h</kbd> context help to be maintained.

**Comment by tony37** [comment]
I have currently installed the Help pages on the schoolserver. Each page 
can be separately downloaded by Browse (and with a patch to ReadFile and 
adding zip  as a mimetime) can be displayed independent of the 
schoolserver. This enables users to take advantage of the information 
without requiring the storage space for the entire set of pages. This 
technique also enables help pages to be displayed for individual 
activities. Agreed, this approach does not support links between pages.

Tony

**Comment by quozl** [comment]
Tony, if you're concerned about storage space, you're probably talking about XO-1 with Fedora 18 and OLPC OS 13.2.9.  On those systems, the size of Help is a worry, at 19MB.  I don't plan to use this change or the other changes to Help in the next version of OLPC OS for XO-1.  I'll probably be cherry-picking only the changes to help for activities that are included.

**Comment by tony37** [comment]
There are also a large number of XO-1.5 with 2GB store in the field.

Tony

**Comment by quozl** [comment]
@octamois, any news?

**Comment by rhl-bthr** [comment]
Stale; Needs more work.

@octamois if you plan to fix the same, please reopen the PR with the fixes

**Pull request closed without merging**
