### PR TITLE
Port WebKit 3.0 to WebKit2 4.0 API

### PR DESCRIPTION
**Pull request by chimosky**

### CODE REVIEW

**Comment by chimosky** [comment]
@quozl, kindly review.

**Comment by quozl** [comment]
Thanks.  Reviewed to fea2c3a.

* [x] change the name of the callback; as it was named consistently with the signal, and now isn't,
* [x] change the name and number of arguments of the callback to match the documentation; as the callback no longer executes properly,
* [x] remove your change to `html/es/html`; it is unrelated to the port,
* [ ] test and finish porting; there are other changes you've yet to make, as the activity does work correctly; images are not loading, and the back button is not available after the first click; these problems are so severe you would have noticed them if you had tested, so it looks like you were not yet at the stage of testing,
* [x] use more detail in commit messages, see [guide to contributing](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits); in particular your removal of [`set_full_content_zoom`](https://lazka.github.io/pgi-docs/WebKit-3.0/classes/WebView.html#WebKit.WebView.set_full_content_zoom) is unfortunate, yet you didn't explain why you removed it rather than use an alternative.

**Comment by chimosky** [comment]
Changes made 
- [x] change the name of the callback; as it was named consistently with the signal, and now isn't,
- [x] remove your change to html/es/html; it is unrelated to the port,

> - [x] test and finish porting; there are other changes you've yet to make, as the activity does work correctly; images are not loading, and the back button is not available after the first click; these problems are so severe you would have noticed them if you had tested, so it looks like you were not yet at the stage of testing,

Images are loading properly for me, the back button isn't available on the first click it is on the second -  click on something else first, could be home button; also occurs in [v20](http://activities.sugarlabs.org/en-US/sugar/addon/4051) - 

> - [x] use more detail in commit messages, see guide to contributing; in particular your removal of set_full_content_zoom is unfortunate, yet you didn't explain why you removed it rather than use an alternative.

Noted.

**Comment by quozl** [comment]
> the back button isn't available on the first click it is on the second - click on something else first, could be home button; also occurs in v20 -

In my tests, it does not occur in v20 on Fedora 18, or v20 on Ubuntu 18.04.

* [ ] Please fix the back button, thanks.

Reviewed to 3af8291.

* [ ] You've removed the zoom in and zoom out buttons.  Please put them back and make them work properly with the WebKit2 API.  Thanks!

**Comment by chimosky** [comment]
Just thought i should [share](https://lists.webkit.org/pipermail/webkit-gtk/2011-December/000861.html), I'll see if i can implement them.

**Comment by quozl** [comment]
Thanks, interesting.  I imagine you will need to call `set_zoom_level` in the zoom in and out callbacks.  In your https://github.com/sugarlabs/help-activity/pull/3/commits/7c4d34d9b405d00af310975471c0309328983d27 what's your purpose in calling `set_zoom_level` and passing the level that it already has set?  Is there some needed side-effect?

**Comment by chimosky** [comment]
As `set_full_content_zoom` was removed in fea2c3a, i added it to serve as a replacement.

**Comment by chimosky** [comment]
@quozl the current zoom level seems to be working properly but requires an opposite reaction before it works again - you zoom in once then zoom out before you can zoom in again -, so basically the both buttons only work once not on multiple clicks.

**Comment by quozl** [comment]
Thanks.  Let me know when you have it working correctly; zoom buttons should work as they did before.

**Comment by chimosky** [comment]
@quozl kindly review.

**Comment by quozl** [comment]
Duplicate of https://github.com/godiard/help-activity/pull/99

**Pull request closed without merging**
